language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 7.2
  - 7.3
  - 7.4

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=4.9 WP_MULTISITE=0
  - WP_VERSION=5.4 WP_MULTISITE=0

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit
